// <auto-generated />
using System;
using Mayhem.Dal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mayhem.Dal.Migrations
{
    [DbContext(typeof(MayhemDataContext))]
    [Migration("20230121111926_NewTableVoteCategory")]
    partial class NewTableVoteCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mayhem.Dal.Tables.GameUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("VoteCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Wallet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("VoteCategoryId");

                    b.ToTable("GameUser", (string)null);
                });

            modelBuilder.Entity("Mayhem.Dal.Tables.GameUserBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("LastBlock")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModificationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GameUserBlocks");
                });

            modelBuilder.Entity("Mayhem.Dal.Tables.VoteCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InvestorCategory")
                        .HasColumnType("int");

                    b.Property<int>("VotePower")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VoteCategories");
                });

            modelBuilder.Entity("Mayhem.Dal.Tables.GameUser", b =>
                {
                    b.HasOne("Mayhem.Dal.Tables.VoteCategory", "VoteCategory")
                        .WithMany()
                        .HasForeignKey("VoteCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VoteCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
